{% set version = "0.8.0" %}

package:
  name: pytest-jupyter-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-jupyter/pytest_jupyter-{{ version }}.tar.gz
  sha256: 842817c300802c8608676bbb1460ba0081f2688cf5cb55b87d7bad5dcb0e9729

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7

outputs:
  - name: pytest-jupyter
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps
      noarch: python
    requirements:
      host:
        - python >=3.7
        - pip
        - hatchling
      run:
        - python >=3.7
        - jupyter_core
        - pytest
      run_constrained:
        # the hard `run` dependencies are in sub-packages
        - jupyter_server >=1.21
        - jupyter_client >=7.4
        - ipykernel >=6.14
        - nbformat >=5.3
    test:
      source_files:
        - tests
      imports:
        - pytest_jupyter
        - pytest_jupyter.jupyter_core
      commands:
        - pip check
      requires:
        - pip

  - name: pytest-jupyter-client
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - {{ pin_subpackage("pytest-jupyter", max_pin="x.x.x") }}
        - ipykernel
        - jupyter_client
        - python >=3.7
    test:
      imports:
        - pytest_jupyter
        - pytest_jupyter.jupyter_client
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://pypi.org/project/pytest-jupyter
      summary: A pytest plugin for testing Jupyter libraries and extensions. (with client dependencies)
      dev_url: https://github.com/jupyter-server/pytest-jupyter
      license: BSD-3-Clause
      license_file: LICENSE

  - name: pytest-jupyter-server
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - {{ pin_subpackage("pytest-jupyter-client", max_pin="x.x.x") }}
        - jupyter_server
        - python >=3.7
    test:
      source_files:
        - tests
      imports:
        - pytest_jupyter
        - pytest_jupyter.jupyter_server
      commands:
        - pip check
        - cd tests && pytest -vv --cov=pytest_jupyter --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=90
      requires:
        - pip
        - pytest-cov
    about:
      home: https://pypi.org/project/pytest-jupyter
      summary: A pytest plugin for testing Jupyter libraries and extensions. (with server dependencies)
      dev_url: https://github.com/jupyter-server/pytest-jupyter
      license: BSD-3-Clause
      license_file: LICENSE

about:
  home: https://pypi.org/project/pytest-jupyter
  summary: A pytest plugin for testing Jupyter libraries and extensions.
  dev_url: https://github.com/jupyter-server/pytest-jupyter
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  feedstock-name: pytest-jupyter
  recipe-maintainers:
    - blink1073
    - fcollonval
    - conda-forge/jupyter_server
